/** @type {import('tailwindcss').Config} */
import colors from 'tailwindcss/colors'
import tailwindcssAnimate from 'tailwindcss-animate'

export default {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  prefix: "",
  theme: {
    colors: {
      ...colors,
      bistre: "#2E220C",
      blue: "#006AC1",
      blue500: "rgb(29, 155, 209)",
      orange2: { DEFAULT: "#FFBA38", light: "#FFBA3866" },
      orange4: "#FFE8BD",
      orange5: "#E09200",
      yellow: "#FFBA38",
      yellow2: "#D7DB22",
      yellow4: "#F6F8C2",
      violet2: "#A97AEF",
      violetLight: "#F7F2FD",
      gray2: "#A09C95",
      gray3: "#E2E1DE",
      gray4: "#605D58",
      gray5: "#F2F1F0",
      gray6: "#545454",
      gray96: "#F6F6F6",
      gray97: "#F7F7F7",
      gray98: "#F4F4F5",
      gray100: "#F8F7F6",
      gray300: "#DADAD8",
      gray400: "#C4C3C1",
      gray500: "#9D9B98",
      gray600: "#7E7C77",
      gray700: "#57544E",
      gray800: "#3B3730",
      gray900: "#EFEFEE",
      gray950: "#1B1305",
      spanishGray: "#97948F",
      red2: "#EB5A2D",
      red3: "#DF261A",
      red4: { DEFAULT: "#E32900", light: "#E329001A" },
      redOrange: "#FD4308",
      alert: "#FDE4B0",
      green: {
        DEFAULT: "#E9F5ED",
        foreground: "#24B556",
        grass: "#08A93F",
        light: "#D5FFC9",
      },
      rose: { DEFAULT: "#FFE1D9", light: "#FFF9F7", 600: "#E11D48" },
      golden: { DEFAULT: "#FFBA18", light: "#FEF7C1", lightest: "#FEF7C1" },
      teal: { DEFAULT: "#0B9B8A", light: "#B8EAE0", lightest: "#92C7C1" },
      cherry: { DEFAULT: "#E5484D", light: "#FFCDCE", lightest: "#ECAFB0" },
      blaze: { DEFAULT: "#F76B15" },
      slack: {
        background: "#222529",
        text: "#D1D2D3",
        divider: "#373A3E",
        header: "#FFFFFF",
        context: "#9B9B9B",
      },
      coral: "#FF8660",
      greenForeground: "#24B556",
      lace: "#FFF5E2",
      oceanBlue: "#3182bd",
      pearlGray: "rgba(218, 218, 216, 0.30)",
      black: colors.black,
      slate: colors.slate,
      white: colors.white,
      gray: colors.gray,
      emerald: { ...colors.emerald, DEFAULT: colors.emerald, 600: "#059669" },
      indigo: colors.indigo,
      transparent: "transparent",
    },
    extend: {
      colors: {
        border: "var(--border)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "calc(var(--radius) + 2px)",
        md: "var(--radius)",
        sm: "calc(var(--radius) - 2px)",
        xs: "calc(var(--radius) - 4px)",
      },
      lineHeight: {
        3.25: "13px",
        3.5: "14px",
        3.75: "15px",
        4.5: "18px",
        "13px": "13px",
        "15px": "15px",
        "18px": "18px",
      },
      fontFamily: {
        sans: ["var(--font-metro)"],
      },
      boxShadow: {
        modal: "0px 4px 30px 0px rgba(0, 0, 0, 0.20)",
        drawer:
          "0px 0px 30px 0px rgba(0, 0, 0, 0.05), 0px 0px 70px 0px rgba(0, 0, 0, 0.03), 0px 4px 50px 0px rgba(0, 0, 0, 0.05)",
      },
      spacing: {
        4.5: "1.125rem",
        7.5: "1.875rem",
        12.5: "3.125rem",
        18: "4.5rem",
        13: "3.25rem",
        25: "4.75rem",
        29: "7.25rem",
        70: "17.5rem",
        95: "23.75rem",
        113: "28.25rem",
        140: "35rem",
        200: "800px",
      },
      transitionProperty: {
        width: "width",
      },
      keyframes: {
        slideIn: {
          from: { transform: "translateY(100%)" },
          to: { transform: "translateY(0)" },
        },
        hide: {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        swipeOut: {
          from: { transform: "translateY(var(--radix-toast-swipe-end-y))" },
          to: { transform: "translateY(100%)" },
        },
        typing: {
          "0%, 50%": { opacity: "1" },
          "51%, 100%": { opacity: "0" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        scaleIn: {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
      },
      animation: {
        slideIn: "slideIn 150ms cubic-bezier(0.16, 1, 0.3, 1)",
        hide: "hide 100ms ease-in",
        swipeOut: "swipeOut 100ms ease-out",
        "pulse-slow": "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "bounce-slow": "bounce 2s infinite",
        typing: "typing 1s ease-in-out infinite",
        "fade-in": "fadeIn 300ms ease-out",
        "scale-in": "scaleIn 200ms ease-out",
        shimmer: "shimmer 1.5s linear infinite",
      },
    },
  },
  plugins: [tailwindcssAnimate],
};
